name: Auto-increment Patch Version on Merge Commit

on:
  push:
    branches:
      - main

jobs:
  increment-patch-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Increment version patch
        run: |
          git show --no-patch --format=%P $GITHUB_SHA | grep -q " " && true
          NEW_VERSION=`npm version patch --no-git-tag-version`
          echo "Updating package.json with $NEW_VERSION"
          sed -i "s/\"version\": .*/\"version\": \"$NEW_VERSION\",/" package.json
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --local user.name "$GITHUB_ACTOR"
          git add package.json
          git commit -m "Incremented patch version to $NEW_VERSION"
          git push