name: Auto-increment Patch Version on Merge Commit

on:
  push:
    branches:
      - main

jobs:
  increment-patch-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if it's a merge commit
        id: check_merge_commit
        run: git show --no-patch --format=%P $GITHUB_SHA | grep -q " "

      - name: Increment patch version
        if: steps.check_merge_commit.outputs.return-value == '0'
        id: increment_version
        run: |
          npm version patch --no-git-tag-version

      - name: Get new version
        if: steps.check_merge_commit.outputs.return-value == '0'
        run: echo "New version: ${{steps.increment_version.outputs.new_version}}"

      - name: Update package.json
        if: steps.check_merge_commit.outputs.return-value == '0'
        run: |
          NEW_VERSION=${{ steps.increment_version.outputs.new_version }}
          sed -i "s/\"version\": .*/\"version\": \"$NEW_VERSION\",/" package.json

      - name: Commit changes
        if: steps.check_merge_commit.outputs.return-value == '0'
        run: |
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --local user.name "$GITHUB_ACTOR"
          git add package.json
          git commit -m "Incremented patch version to $NEW_VERSION"
          git push
