name: Auto-increment Patch Version on Merge Commit

on:
  push:
    branches:
      - main

jobs:
  increment-patch-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Increment version patch
        run: |
          chmod +x .github/scripts/incrementPatchVersionAndPush.sh
          .github/scripts/incrementPatchVersionAndPush.sh
